FROM ubuntu
MAINTAINER Daniel Wei <danielwii0326@gmail.com>

ADD https://raw.githubusercontent.com/danielwii/docker_base_scripts/master/entrypoint.sh /entrypoint.sh
RUN chmod +x entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["echo", "^_^"]
